//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ID { get; set; }
        public string TenSanPham { get; set; }
        public string MoTaNgan { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public int SoLuong { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> LuotMua { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public int IDLoai { get; set; }
        public int IDHang { get; set; }
        public string MoTaChiTiet { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
